title: "Anirban Chakrabarti"
description: "Personal webpage highlighting research, education, and professional activities."
baseurl: ""
url: "https://anirban2crypto.github.io/anirban_chakrabarti/"

theme: minima

author: "Anirban Chakrabarti"
email: anirban@example.com

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_username: anirbanchakrabarti
linkedin_username: anirbanchakrabarti
scholar: https://scholar.google.com/citations?user=abcdefg1234

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

minima:
  skin: classic
  include_css:
    - assets/css/style.css
