title: "Anirban Chakrabarti"
description: ""
baseurl: "/anirban_chakrabarti"
url: "https://anirban2crypto.github.io"

theme: minima

author: ""
email: anirban2chakrabarti@gmail.com

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

github_username: anirban2crypto
linkedin_username: anirban-chakrabarti-346bba28
scholar: https://scholar.google.com/citations?user=Hj7fF9QAAAAJ

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

minima:
  skin: classic
  include_css:
    - assets/css/style.css

defaults:
  - scope:
      path: ""
      ext: "md"
    values:
      layout: default
