title: "Anirban Chakrabarti"
#description: >-
#  Personal webpage highlighting research, education, and professional activities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anirban2crypto.github.io/anirban_chakrabarti/" # replace with your GitHub Pages URL

theme: minima

# Optional settings
author: "Anirban Chakrabarti"
email: your.email@example.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social links (optional)
github_username: anirbanchakrabarti
linkedin_username: anirbanchakrabarti
scholar: https://scholar.google.com/citations?user=XXXXXX

# Exclude these files from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  
minima:
  skin: classic
  include_css: ["assets/css/style.css"]
  